local Terrain = require("shared/terrain/Terrain")
local InGameScreen = require("javaclassdefs/InGameScreen")
local Skin = require("javaclassdefs/Skin")
local Stage = require("javaclassdefs/Stage")

local record DeployMenu

    show: function(DeployMenu, Terrain)
    clear: function(DeployMenu)
    metamethod __call: function(DeployMenu, InGameScreen, Skin, Stage, function): DeployMenu
end

return DeployMenu