local Unit = require("shared/unit/Unit")
local InGameScreen = require("javaclassdefs/InGameScreen")
local Skin = require("javaclassdefs/Skin")
local Stage = require("javaclassdefs/Stage")
local Map = require("shared/Map")

local record TargetMenu

    show: function(TargetMenu, Unit, {Unit}, boolean)
    clear: function(TargetMenu)
    metamethod __call: function(TargetMenu, InGameScreen, Skin, Stage, Map, function, function): TargetMenu
end

return TargetMenu